name: shoes_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  another_flutter_splash_screen: ^1.1.5
  awesome_notifications: ^0.7.4+1
  badges: ^3.1.2
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_core_desktop: ^1.0.2
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_sign_in: ^6.1.5
  iconsax: ^0.0.8
  image_picker: ^1.0.4
  lottie: ^2.6.0
  switcher: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/AppIcon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icons/AppIcon.png"
    icon_size: 48

flutter_assets:
  assets_path: assets/
  output_path: lib/Helpers/
  filename: images.dart
  field_prefix: null

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/static/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway/static/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway/static/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway/static/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway/static/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway/static/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway/static/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway/static/Raleway-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500

        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 300
