name: shoes_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  another_flutter_splash_screen: ^1.1.5
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_assets:
  assets_path: assets/
  output_path: lib/Helpers/
  filename: images.dart
  field_prefix: null

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/static/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway/static/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway/static/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway/static/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway/static/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway/static/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway/static/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway/static/Raleway-Black.ttf
          weight: 900
