// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpBgcfKCdPp2NbPEmfXWIYBgxcU-ae6A4',
    appId: '1:711507220797:web:128ec766c1ae13412c4d54',
    messagingSenderId: '711507220797',
    projectId: 'sonic-702ce',
    authDomain: 'sonic-702ce.firebaseapp.com',
    storageBucket: 'sonic-702ce.appspot.com',
    measurementId: 'G-H8H637783L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_eMQv3FQyiSwPtDqnHSF24jTNC2e1v_E',
    appId: '1:711507220797:android:d567071caa014c822c4d54',
    messagingSenderId: '711507220797',
    projectId: 'sonic-702ce',
    storageBucket: 'sonic-702ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5GPQ1OsruxIeso4boTs96jNDuAnjt6I',
    appId: '1:711507220797:ios:0f0b157966ce36b82c4d54',
    messagingSenderId: '711507220797',
    projectId: 'sonic-702ce',
    storageBucket: 'sonic-702ce.appspot.com',
    iosClientId: '711507220797-b69fivr6s3p91nor81ttdvo3kumlkj3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy5GPQ1OsruxIeso4boTs96jNDuAnjt6I',
    appId: '1:711507220797:ios:6b83881fdaff8c832c4d54',
    messagingSenderId: '711507220797',
    projectId: 'sonic-702ce',
    storageBucket: 'sonic-702ce.appspot.com',
    iosClientId: '711507220797-mjl0hl37jetihl74gig7tp5m7p49bpuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesStore.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpBgcfKCdPp2NbPEmfXWIYBgxcU-ae6A4',
    appId: '1:711507220797:web:59748e0385695e5e2c4d54',
    messagingSenderId: '711507220797',
    projectId: 'sonic-702ce',
    authDomain: 'sonic-702ce.firebaseapp.com',
    storageBucket: 'sonic-702ce.appspot.com',
    measurementId: 'G-LV1WTX3VF4',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBpBgcfKCdPp2NbPEmfXWIYBgxcU-ae6A4',
    appId: '1:711507220797:web:5b03fb42099d61262c4d54',
    messagingSenderId: '711507220797',
    projectId: 'sonic-702ce',
    authDomain: 'sonic-702ce.firebaseapp.com',
    storageBucket: 'sonic-702ce.appspot.com',
    measurementId: 'G-H1H778WB4M',
  );
}
